### PR TITLE
Conform code to pep8 style

### PR DESCRIPTION
**Pull request by javanlacerda**
- Solving the issue #11
- Remove unused imports
- Remove unused variables
- Split strings and expressions that are bigger then 79 characters
- Remove white-spaces
- Add a white line in the end of files
- Fix the indentation

### CODE REVIEW

**Review by rafaelvfalc — COMMENTED** [review]
Thank you for this implementation. Everything looks good to me. I just have a couple of commentaries:

1 - The CI tests are not successful, can you verify this issue?
2 - I believe that this version of the code should be tested together with the PEP8 versions of the other components before be successfully merged.

**Review by matheuscmelo — CHANGES_REQUESTED** [review]
Visualizer is creating Grafana's dashboard but isn't generating it's URL in time. Please investigate.

**Comment by javanlacerda** [comment]
The bugs are fixed. It's not possible to see the solution because I did squash.

**Review by matheuscmelo — APPROVED** [review]

**Comment by matheuscmelo** [comment]
LGTM

**Review by clenimar — APPROVED** [review]
good job. thanks!

**Review by liliarsampaio — APPROVED** [review]

**Pull request merged**
